const allRecipes = [
  {
    slug: "creamy-tomato-basil-soup",
    title: "Creamy Tomato Basil Soup",
    category: "Soup",
    image: "./images/tomato-soup.jpeg",
    description:
      "This comforting recipe is made with fresh tomatoes, basil, and a touch of cream.",
    cookTime: "25 MIN",
    prepTime: "10 MIN",
    servings: "4",
    ingredients: [
      "2 tbsp olive oil",
      "1 onion, chopped",
      "2 cloves garlic, minced",
      "800g canned tomatoes, crushed",
      "4 cups vegetable broth",
      "1/2 cup fresh basil leaves",
      "1/4 cup heavy cream",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Heat olive oil in a large pot over medium heat. Add onion and cook until soft and translucent, about 5 minutes.",
      "Stir in garlic and cook for another minute until fragrant.",
      "Pour in crushed tomatoes and vegetable broth. Bring the mixture to a simmer.",
      "Reduce heat, cover, and let it simmer for 20 minutes to allow the flavors to meld.",
      "Remove the pot from the heat and stir in fresh basil. Use an immersion blender to blend the soup until it's smooth.",
      "Stir in the heavy cream and season with salt and pepper. Serve hot.",
    ],
  },
  {
    slug: "spicy-shrimp-tacos",
    title: "Spicy Shrimp Tacos",
    category: "Tacos",
    image: "./images/shrimp-tacos.jpeg",
    description:
      "These tacos are loaded with juicy shrimp that have been marinated in a spicy mix of flavors.",
    cookTime: "15 MIN",
    prepTime: "20 MIN",
    servings: "3",
    ingredients: [
      "450g shrimp, peeled and deveined",
      "2 tbsp chili powder",
      "1 tsp cumin",
      "1/2 tsp paprika",
      "1 tbsp olive oil",
      "8 small tortillas",
      "Toppings: avocado, cilantro, lime wedges",
    ],
    instructions: [
      "In a bowl, toss shrimp with chili powder, cumin, and paprika.",
      "Heat olive oil in a pan over medium-high heat. Add shrimp and cook for 2-3 minutes per side, until pink and cooked through.",
      "Warm the tortillas. Fill each tortilla with shrimp and your favorite toppings. Serve immediately.",
    ],
  },
  {
    slug: "chicken-parmesan",
    title: "Chicken Parmesan",
    category: "Italian",
    image: "./images/chicken-parmesan.jpeg",
    description:
      "This classic Italian dish features breaded chicken breasts cooked to crispy perfection.",
    cookTime: "30 MIN",
    prepTime: "15 MIN",
    servings: "2",
    ingredients: [
      "2 boneless, skinless chicken breasts",
      "1 cup breadcrumbs",
      "1/2 cup grated Parmesan cheese",
      "1 large egg, beaten",
      "2 tbsp vegetable oil",
      "1 cup marinara sauce",
      "1 cup shredded mozzarella cheese",
    ],
    instructions: [
      "Preheat oven to 400°F ($200^circ C$).",
      "Combine breadcrumbs and Parmesan cheese in a shallow dish. Dip each chicken breast into the beaten egg, then coat in the breadcrumb mixture.",
      "Heat oil in an oven-safe skillet over medium-high heat. Cook chicken for 3-4 minutes per side until golden brown.",
      "Pour marinara sauce over the chicken, top with mozzarella cheese, and bake for 10-15 minutes, until cheese is melted and bubbly.",
    ],
  },
  {
    slug: "chocolate-chip-cookies",
    title: "Chocolate Chip Cookies",
    category: "Dessert",
    image: "./images/chocolate-chip-cookies.jpg",
    description:
      "These cookies are the perfect blend of chewy and crispy, with gooey melted chocolate.",
    cookTime: "12 MIN",
    prepTime: "10 MIN",
    servings: "12 cookies",
    ingredients: [
      "1/2 cup butter, softened",
      "1/2 cup brown sugar",
      "1/4 cup granulated sugar",
      "1 large egg",
      "1 tsp vanilla extract",
      "1 1/2 cups all-purpose flour",
      "1/2 tsp baking soda",
      "1/4 tsp salt",
      "1 cup chocolate chips",
    ],
    instructions: [
      "Preheat oven to 375°F ($190^circ C$).",
      "In a large bowl, cream together butter and both sugars until light and fluffy.",
      "Beat in the egg and vanilla.",
      "In a separate bowl, whisk together flour, baking soda, and salt. Gradually add to the butter mixture and mix until just combined.",
      "Stir in the chocolate chips.",
      "Drop rounded tablespoons of dough onto ungreased baking sheets.",
      "Bake for 10-12 minutes, or until edges are golden brown. Let cool on the baking sheet for a few minutes before transferring to a wire rack.",
    ],
  },
  {
    slug: "crispy-masala-dosa",
    title: "Crispy Masala Dosa",
    category: "South Indian",
    image: "./images/masala-dosa.jpeg",
    description:
      "A classic South Indian crepe stuffed with spiced potato filling.",
    cookTime: "20 MIN",
    prepTime: "8 HRS (soaking)",
    servings: "4",
    ingredients: [
      "1 cup urad dal (split black lentils)",
      "2 cups rice",
      "1/2 tsp fenugreek seeds",
      "Salt to taste",
      "For potato filling: potatoes, onions, green chilies, spices",
    ],
    instructions: [
      "Soak rice, urad dal, and fenugreek seeds together in water for at least 8 hours.",
      "Drain and grind to a smooth batter with a little water. Ferment overnight.",
      "To make the filling, boil and mash potatoes. Sauté onions and green chilies, then add the potatoes and spices.",
      "Heat a non-stick pan, pour a ladle of batter, and spread thinly in a circular motion. Drizzle with oil and cook until golden and crispy.",
      "Place a spoonful of potato filling in the center, fold the dosa, and serve hot with sambar and chutney.",
    ],
  },
  {
    slug: "soft-idli",
    title: "Soft Idli",
    category: "South Indian",
    image: "./images/idli.jpg",
    description: "Steamed rice cakes served with chutney and sambar.",
    cookTime: "15 MIN",
    prepTime: "8 HRS (soaking)",
    servings: "4",
    ingredients: [
      "1 cup urad dal",
      "2 cups idli rice",
      "1 tsp fenugreek seeds",
      "Salt to taste",
    ],
    instructions: [
      "Soak urad dal, rice, and fenugreek seeds separately for 8 hours.",
      "Grind the soaked dal and rice into a smooth batter. Mix them together with salt and let it ferment overnight.",
      "Pour the batter into greased idli molds. Steam in an idli cooker for 10-15 minutes.",
      "Serve hot with coconut chutney and sambar.",
    ],
  },
  {
    slug: "medu-vada",
    title: "Medu Vada",
    category: "South Indian",
    image: "./images/vada.jpeg",
    description: "Crispy lentil fritters, perfect with coconut chutney.",
    cookTime: "20 MIN",
    prepTime: "4 HRS (soaking)",
    servings: "4",
    ingredients: [
      "1 cup urad dal",
      "2 green chilies, finely chopped",
      "1 inch ginger, grated",
      "1/2 tsp black peppercorns",
      "Salt to taste",
      "Oil for frying",
    ],
    instructions: [
      "Soak urad dal for 4 hours. Drain and grind it into a coarse batter with minimal water. Do not make it too smooth.",
      "Add chopped green chilies, grated ginger, black peppercorns, and salt to the batter. Mix well.",
      "Heat oil in a deep pan. Wet your hands, take a small portion of the batter, shape it into a doughnut, and gently drop it into the hot oil.",
      "Fry until golden brown and crispy. Serve hot with coconut chutney or sambar.",
    ],
  },
  {
    slug: "vegetable-sambar",
    title: "Vegetable Sambar",
    category: "South Indian",
    image: "./images/sambar.jpeg",
    description: "A flavorful lentil stew with vegetables and spices.",
    cookTime: "30 MIN",
    prepTime: "15 MIN",
    servings: "4",
    ingredients: [
      "1 cup toor dal (split pigeon peas)",
      "1/2 tsp turmeric powder",
      "Mixed vegetables (carrots, beans, pumpkin)",
      "1 onion, chopped",
      "1 tomato, chopped",
      "2 tbsp sambar powder",
      "Tamarind pulp",
      "Salt to taste",
      "For tempering: mustard seeds, curry leaves, oil, asafoetida",
    ],
    instructions: [
      "Cook toor dal with turmeric powder until soft and mashed. Set aside.",
      "In a separate pan, sauté onions, tomatoes, and mixed vegetables. Add sambar powder and tamarind pulp.",
      "Add the cooked dal to the vegetables. Mix well, add salt, and bring to a simmer.",
      "Prepare tempering by heating oil and adding mustard seeds, curry leaves, and asafoetida. Pour it over the sambar.",
      "Serve hot with idli or dosa.",
    ],
  },
  {
    slug: "chana-masala",
    title: "Chana Masala",
    category: "Indian Curry",
    image: "./images/chana_masala.jpg",
    description:
      "A spicy and tangy chickpea curry, a popular dish from North India.",
    cookTime: "30 MIN",
    prepTime: "15 MIN",
    servings: "4",
    ingredients: [
      "1 tbsp oil",
      "1 onion, finely chopped",
      "2 tomatoes, pureed",
      "1 tsp ginger-garlic paste",
      "1 can (15 oz) chickpeas, rinsed",
      "1 tsp cumin powder",
      "1 tsp coriander powder",
      "1/2 tsp red chili powder",
      "1 tsp chana masala powder",
      "Salt to taste",
      "Fresh cilantro for garnish",
    ],
    instructions: [
      "Heat oil in a pan. Add chopped onion and sauté until golden.",
      "Stir in ginger-garlic paste and cook for one minute.",
      "Add tomato puree and cook until the oil separates.",
      "Mix in cumin, coriander, red chili, and chana masala powders. Cook for a minute.",
      "Add chickpeas and enough water to get the desired consistency. Season with salt.",
      "Bring to a boil, then simmer for 10-15 minutes. Garnish with fresh cilantro before serving.",
    ],
  },
  {
    slug: "egg-bhurji",
    title: "Egg Bhurji",
    category: "Indian Scramble",
    image: "./images/egg_bhurji.jpg",
    description:
      "A flavorful and spicy Indian-style scrambled eggs, perfect for a quick meal.",
    cookTime: "10 MIN",
    prepTime: "5 MIN",
    servings: "2",
    ingredients: [
      "2 tbsp oil or butter",
      "1 onion, finely chopped",
      "1 tomato, finely chopped",
      "2 green chilies, chopped",
      "1/2 tsp ginger-garlic paste",
      "3 eggs, beaten",
      "1/4 tsp turmeric powder",
      "1/2 tsp red chili powder",
      "Salt to taste",
      "Fresh cilantro for garnish",
    ],
    instructions: [
      "Heat oil or butter in a pan. Add chopped onion and green chilies. Sauté until the onion softens.",
      "Add ginger-garlic paste and cook for one minute.",
      "Stir in chopped tomatoes, turmeric, and red chili powder. Cook until tomatoes are soft.",
      "Pour in the beaten eggs. Scramble them quickly with a spatula until cooked but still soft.",
      "Season with salt and garnish with fresh cilantro. Serve hot with bread or roti.",
    ],
  },
  {
    slug: "coconut-chutney",
    title: "Coconut Chutney",
    category: "South Indian",
    image: "./images/coconut.jpg",
    description:
      "A classic South Indian condiment made from fresh coconut, chilies, and tempered spices.",
    cookTime: "5 MIN",
    prepTime: "10 MIN",
    servings: "4",
    ingredients: [
      "1 cup fresh grated coconut",
      "2 green chilies",
      "1 inch ginger",
      "1/4 cup roasted chana dal (dalia)",
      "1/2 tsp tamarind pulp",
      "Salt to taste",
      "Water as needed for grinding",
      "For tempering: 1 tsp oil, 1/2 tsp mustard seeds, 1 red chili, 1 sprig curry leaves, pinch of asafoetida",
    ],
    instructions: [
      "In a blender, combine grated coconut, green chilies, ginger, roasted chana dal, tamarind pulp, and salt. Add a little water and blend to a smooth paste.",
      "Transfer the chutney to a serving bowl.",
      "Heat oil in a small pan. Add mustard seeds and let them splutter. Add red chili, curry leaves, and asafoetida. Cook for a few seconds.",
      "Pour the tempering over the chutney and mix well. Serve with idli, dosa, or vada.",
    ],
  },
  {
    slug: "tomato-chutney",
    title: "Tomato Chutney",
    category: "South Indian",
    image: "./images/tomato_chutney.jpg",
    description:
      "A spicy and tangy chutney made with tomatoes, garlic, and red chilies.",
    cookTime: "15 MIN",
    prepTime: "5 MIN",
    servings: "4",
    ingredients: [
      "2 tomatoes, chopped",
      "4-5 dried red chilies",
      "2-3 cloves garlic",
      "1 tsp oil",
      "1/2 tsp cumin seeds",
      "Salt to taste",
      "For tempering: 1 tsp oil, 1/2 tsp mustard seeds, 1 sprig curry leaves",
    ],
    instructions: [
      "Heat oil in a pan. Add red chilies, garlic, and cumin seeds. Sauté for a minute.",
      "Add chopped tomatoes and a pinch of salt. Cook until the tomatoes are soft and mushy.",
      "Let the mixture cool down completely. Transfer it to a blender and blend to a smooth paste. Add water if necessary to achieve the desired consistency.",
      "Pour the chutney into a bowl.",
      "Heat oil in a small pan for tempering. Add mustard seeds and let them splutter. Add curry leaves.",
      "Pour the tempering over the chutney and serve.",
    ],
  },
];
